status_dwarf/views.py
from datetime import timezone, datetime

from flask import Blueprint, render_template, abort, current_app, Response

from status_dwarf.models import Target, session, Status
from status_dwarf.utils import div_ceil, _

views_bp = Blueprint("views", __name__)


@views_bp.route("/", defaults={"page": 1})
@views_bp.route("/<int:page>")
def index(page: int) -> str:
    all_targets = session.query(Target).all()
    page_size = current_app.config["PAGE_SIZE"]
    page_count = div_ceil(len(all_targets), page_size)
    if page > page_count and page != 1:
        return abort(404)
    context = {
        "targets": all_targets[(page - 1) * page_size: page * page_size],
        "next_page": page + 1 if page_count > page else None,
        "prev_page": page - 1 if page > 1 else None,
        "show_positive_message": not Target.any_target_down(),
        "Status": Status,
    }
    return render_template("index.html", **context)


@views_bp.route("/atom.xml")
@views_bp.route("/atom")
def atom() -> Response:
    if not current_app.config["ATOM_ENABLED"]:
        return abort(404)
    return Response(render_template("atom.xml", targets=session.query(Target).all(),
                                    now=datetime.now(timezone.utc).isoformat()),
                    mimetype='text/xml')


def error_handler(e) -> tuple[str, int]:
    error_descriptions = {
        500: _("An error has occurred. Please try again later."),
        404: _("The requested URL was not found on the server.")
    }
    e.description = error_descriptions.get(e.code, e.description)
    return render_template("error.html", exception=e), e.code

status_dwarf/templates/error.html
{% extends 'generic.html' %}
{% block content %}
    <div class="center-box-container">
        <div class="center-box-content bg-red">
            <h1 class="m-0">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                     viewBox="0 0 24 24" fill="none" stroke="currentColor"
                     stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="align-middle">
                    <circle cx="12" cy="12" r="10"></circle>
                    <path d="m15 9-6 6"></path>
                    <path d="m9 9 6 6"></path>
                </svg>
                <span class="align-middle">{{ exception.code }}</span>
            </h1>
            <p>{{ exception.description }}</p>
            <a href="/">{{ _("Go to homepage") }}</a>
        </div>
    </div>
{% endblock %}

status_dwarf/templates/generic.html
<!doctype html>
<html lang="{{ _.get_lang() }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{{ _(config.APP_NAME) }}</title>
    {% if config.APP_DESCRIPTION %}
        <meta name="description" content="{{ _(config.APP_DESCRIPTION) }}"/>
    {% endif %}
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="white"/>
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="black"/>
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <link rel="icon" type="image/svg+xml" href="{{ url_for('static', filename='images/favicon.svg') }}">
    <link rel="apple-touch-icon" href="{{ url_for('static', filename='images/apple-touch-icon.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fonts.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% if config.ATOM_ENABLED %}
        <link href="{{ url_for('views.atom') }}" type="application/atom+xml" rel="alternate" title="Atom feed alerts"/>
    {% endif %}
    <script defer src="{{ url_for('static', filename='js/datetime.js') }}"></script>
</head>
<body>
<div class="content">
    {% block content %}{% endblock %}
</div>
<footer>
    <span class="faded-text">{{ _(config.FOOTER_TEXT    )|safe }}</span>
    {% if config.ATOM_ENABLED %}
        <a href="{{ url_for('views.atom') }}" aria-label="Atom Feed" class="right-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M4 11a9 9 0 0 1 9 9"></path>
                <path d="M4 4a16 16 0 0 1 16 16"></path>
                <circle cx="5" cy="19" r="1"></circle>
            </svg>
        </a>
    {% endif %}
</footer>
</body>
</html>

status_dwarf/templates/index.html
{% extends 'generic.html' %}
{% block content %}
    <div class="top-container">
        <h1>{{ _(config.APP_NAME) }}</h1>
        {% if config.APP_DESCRIPTION %}
            <p>{{ _(config.APP_DESCRIPTION) }}</p>
        {% endif %}
        <img src="{{ url_for('static', filename='images/app-logo.svg') }}" alt="{{ _("App Logo") }}" class="app-logo"
             width="100">
    </div>
    <div class="monitor" ontouchstart>
        <div class="center-flex">
            {% if not targets %}
                <div class="monitor-summary bg-red">
                    <span class="align-middle">{{ _("No systems are being monitored.") }}</span>
                </div>
            {% elif show_positive_message %}
                <div class="monitor-summary bg-green">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                         viewBox="0 0 24 24" fill="none" stroke="currentColor"
                         stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="align-middle">
                        <circle cx="12" cy="12" r="10"></circle>
                        <path d="m9 12 2 2 4-4"></path>
                    </svg>
                    <span class="align-middle ml-desktop">{{ _("All systems are operational.") }}</span>
                </div>
            {% else %}
                <div class="monitor-summary bg-red">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                         viewBox="0 0 24 24" fill="none" stroke="currentColor"
                         stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="align-middle">
                        <circle cx="12" cy="12" r="10"></circle>
                        <path d="m15 9-6 6"></path>
                        <path d="m9 9 6 6"></path>
                    </svg>
                    <span class="align-middle ml-desktop">{{ _("Some systems are currently down.") }}</span>
                </div>
            {% endif %}
        </div>
        {% for target in targets %}
            <div class="center-flex">
                <div class="target-container">
                    <div class="target-name">
                        {% if target.status == Status.UP %}
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22"
                                 viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                 stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                 class="align-middle text-green">
                                <circle cx="12" cy="12" r="10"></circle>
                                <path d="m9 12 2 2 4-4"></path>
                            </svg>
                        {% elif target.status == Status.DOWN %}
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22"
                                 viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                 stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                 class="align-middle text-red">
                                <circle cx="12" cy="12" r="10"></circle>
                                <path d="m15 9-6 6"></path>
                                <path d="m9 9 6 6"></path>
                            </svg>
                        {% endif %}
                        <span class="align-middle ml{{ " text-" + target.status_color }}">{{ target.name }}</span>
                    </div>
                    <div class="target-content">
                        <span
                            class="faded-text bottom-side-note">{{ _("Average Uptime: ") + target.average_uptime if target.average_uptime }}</span>
                        {% for item in target.get_display_items() %}
                            <div class="status-block{{ " status-block-" + item.status_color }} tooltip">
                                <div class="tooltip-content">
                                    <div class="tooltip-box">
                                        <span class="datetime align-middle">{{ item.formatted_datetime_start }}</span>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round"
                                             class="align-middle tooltip-arrow-right">
                                            <path d="M18 8L22 12L18 16"></path>
                                            <path d="M2 12H22"></path>
                                        </svg>
                                        <div class="tooltip-arrow-down">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                 viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                                 stroke-linecap="round" stroke-linejoin="round"
                                                 class="align-middle">
                                                <path d="M8 18L12 22L16 18"></path>
                                                <path d="M12 2V22"></path>
                                            </svg>
                                        </div>
                                        <span class="datetime align-middle">{{ item.formatted_datetime_end }}</span>
                                        <div class="status-text">
                                            {% if item.status == Status.UP %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18"
                                                     viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                     stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                                     class="align-middle text-green">
                                                    <circle cx="12" cy="12" r="10"></circle>
                                                    <path d="m9 12 2 2 4-4"></path>
                                                </svg>
                                            {% elif item.status == Status.DOWN %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18"
                                                     viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                     stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                                     class="align-middle text-red">
                                                    <circle cx="12" cy="12" r="10"></circle>
                                                    <path d="m15 9-6 6"></path>
                                                    <path d="m9 9 6 6"></path>
                                                </svg>
                                            {% elif item.status == Status.SEMI_DOWN %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18"
                                                     viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                     stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                                     class="align-middle text-yellow">
                                                    <circle cx="12" cy="12" r="10"></circle>
                                                    <line x1="12" x2="12" y1="8" y2="12"></line>
                                                    <line x1="12" x2="12.01" y1="16" y2="16"></line>
                                                </svg>
                                            {% elif item.status == Status.NO_DATA %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18"
                                                     viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                     stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                                     class="align-middle text-gray">
                                                    <circle cx="12" cy="12" r="10"></circle>
                                                    <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
                                                    <path d="M12 17h.01"></path>
                                                </svg>
                                            {% endif %}
                                            <span
                                                class="align-middle{{ " text-" + item.status_color }}">{{ item.status_text }}</span>
                                        </div>
                                        {% if item.uptime_info %}
                                            <div>{{ item.uptime_info }}</div>
                                        {% endif %}
                                        {% if item.downtime_info %}
                                            <div>{{ item.downtime_info }}</div>
                                        {% endif %}
                                        {% if item.no_data_info %}
                                            <div>{{ item.no_data_info }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="chevron-down"></div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if prev_page or next_page %}
            <div class="center-flex">
                {% if prev_page %}
                    <a href="{{ url_for('views.index', page=prev_page) }}" class="btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round" class="align-middle">
                                <path d="M18 15h-6v4l-7-7 7-7v4h6v6z"></path>
                            </svg>
                            <span class="align-middle">{{ _("Previous") }}</span>
                        </div>
                    </a>
                {% endif %}
                {% if next_page %}
                    <a href="{{ url_for('views.index', page=next_page) }}" class="btn">
                        <div>
                            <span class="align-middle">{{ _("Next") }}</span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round" class="align-middle">
                                <path d="M6 9h6V5l7 7-7 7v-4H6V9z"></path>
                            </svg>
                        </div>
                    </a>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}